databases:
  # PostgreSQL Database
  - name: health-tracker-db
    plan: free
    region: frankfurt
    databaseName: health_tracker
    user: health_user

services:
  # Backend Web Service
  - type: web
    name: health-tracker-backend
    env: docker
    plan: free
    region: frankfurt
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: health-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://miniboxgym.pt,https://www.miniboxgym.pt

  # Frontend Static Site
  - type: web
    name: health-tracker-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        value: https://api.miniboxgym.pt
