name: Deploy

on:
  pull_request:
    types: [closed]
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway (environment)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_ENVIRONMENT: production
        run: |
          if [[ "${{ github.base_ref }}" == "main" || "${{ github.base_ref }}" == "master" ]]; then
            export RAILWAY_ENVIRONMENT=production
          else
            export RAILWAY_ENVIRONMENT=qa
          fi
          railway up --service backend --environment $RAILWAY_ENVIRONMENT --ci
          railway up --service frontend --environment $RAILWAY_ENVIRONMENT --ci


